export const DEFAULT_VEHICLE_HEALTH = 100;
export const DEFAULT_VEHICLE_MAX_VELOCITY_X = 50;
export const DEFAULT_VEHICLE_ACCELERATION = 10;
export const DEFAULT_MIN_FRAMES_BEFORE_INITIALIZATION = 7;
export const DEFAULT_MIN_TIME_BEFORE_INITIALIZATION = 30 * 17;

export enum VEHICLE_TYPE_IDENTIFIERS {
  SHIP = 'ship',
  BOAT = 'boat',
}
