export const DEFAULT_PHASE_STEP = 0.1;
export const DEFAULT_TIME_STEP = 1;
export const DEFAULT_AMPLITUDE_MULTIPLIER = 0.95;
export const DEFAULT_FREQUEMCY_MULTIPLIER = 1.01;
export const DEFAULT_MINIMUM_AMPLITUDE = 1;

export const MAXIMUM_INITIAL_AMPLITUDE = 200;

export const MINIMUM_INITIAL_FREQUENCY = 0.005;
export const MAXIMUM_INITIAL_FREQUENCY = 0.01;
