/**
 * Secondary attachment tuning (worklet-safe).
 */

export const secondaryItemTuning = {
  LAGGING_SPRING_STIFFNESS: 180,
  LAGGING_SPRING_DAMPING: 12,
  LAGGING_SPRING_VELOCITY_FACTOR: 0.05,
  LAGGING_SPRING_OFFSET_CLAMP: 15,
  LAGGING_SPRING_PIVOT_WHIPLASH: 2.5,
  /** Crest LaggingSpring — stronger lag + bottom-anchored bend. */
  CREST_SPRING_STIFFNESS: 120,
  CREST_SPRING_DAMPING: 10,
  CREST_SPRING_VELOCITY_FACTOR: 0.08,
  CREST_SPRING_OFFSET_CLAMP: 18,
  CREST_BEND_ANGLE_FACTOR: 0.035,
  CREST_BEND_ANGLE_CLAMP: 0.45,
  CREST_WIND_LIFT_FACTOR: 0.012,
  CREST_WIND_LIFT_CLAMP: 6,
  CREST_PIVOT_WHIPLASH: 3.2,
  PROCEDURAL_CHAIN_SEGMENT_COUNT: 3,
  PROCEDURAL_CHAIN_SEGMENT_LENGTH: 6,
  PROCEDURAL_CHAIN_LAG_PER_SEGMENT: 0.12,
  SHADER_REACTIVE_BASE_OPACITY: 0.85,
  SHADER_REACTIVE_TIER_OPACITY_BOOST: 0.05,
  SHADER_REACTIVE_SPEED_OPACITY_SCALE: 0.0004,
  SHADER_REACTIVE_TIER_OFFSET_SQUEEZE: 1.5,
} as const;
