/** Transparent swimmer start-screen UI (generated by scripts/process_swimmer_ui_assets.py). */

export const swimmerTitleFloodRush = require('../../assets/swimmer/transparent/title-flood-rush.webp');
export const swimmerUiBtnStartGreen = require('../../assets/swimmer/transparent/ui_btn_start_green.webp');
export const swimmerUiChipPanel = require('../../assets/swimmer/transparent/ui_chip_panel.webp');
export const swimmerIconCrownGold = require('../../assets/swimmer/transparent/icon_crown_gold.webp');
export const swimmerIconShopCart = require('../../assets/swimmer/transparent/icon_shop_cart.webp');
export const swimmerTutorialTapArrows = require('../../assets/swimmer/transparent/tutorial_tap_arrows.webp');
export const swimmerTapCursorSprite = require('../../assets/swimmer/transparent/tap-cursor-sprite.webp');

/** Keys registered in RNTGE image cache via `<Asset type="image" name="…" />`. */
export const SWIMMER_UI_IMAGE = {
  titleFloodRush: 'swimmer_title_flood_rush',
  uiBtnStartGreen: 'swimmer_ui_btn_start_green',
  uiChipPanel: 'swimmer_ui_chip_panel',
  iconCrownGold: 'swimmer_icon_crown_gold',
  iconShopCart: 'swimmer_icon_shop_cart',
  tutorialTapArrows: 'swimmer_tutorial_tap_arrows',
  tapCursorSprite: 'swimmer_tap_cursor_sprite',
} as const;

/** Tap-cursor spritesheet (4×3 grid, 1200×896 source). */
export const TAP_CURSOR_SPRITE = {
  frameWidth: 300,
  frameHeight: 298,
  framesPerRow: 4,
  totalFrames: 12,
  frameDurationMs: 75,
  displayRefWidth: 140,
  frameAspect: 300 / 298,
  sideGapSec: 0.35,
} as const;

/** Visible content aspect (width / height) after background removal. */
export const SWIMMER_UI_ASPECT = {
  /** Cropped transparent/title-flood-rush.webp (1398×707). */
  titleFloodRush: 1398 / 707,
  uiBtnStartGreen: 3.8920570264765786,
  uiChipPanel: 0.9562043795620438,
  iconCrownGold: 1.2636103151862463,
  iconShopCart: 1.1213793103448275,
  tutorialTapArrows: 2.608080808080808,
} as const;

/** Gameplay channel width as a fraction of screen (matches ContainerView). */
export const GAMEPLAY_CHANNEL_WIDTH_FRACTION = 0.8;

/** Outer glow on title logo — follows alpha silhouette via Skia drop shadow. */
export const TITLE_LOGO_IMAGE_SHADOW = {
  dx: 0,
  dy: 2,
  blur: 14,
  color: '#000000',
  shadowOnly: true,
} as const;

/** Layout targets on 1080×1920 reference canvas. */
export const SWIMMER_UI_REF = {
  titleGapBelowChip: 20,
  chipSize: 300,
  chipInsetX: 28,
  chipTop: 36,
  ctaWidth: 872,
  ctaBottom: 52,
  tutorialGapAboveCta: 28,
  tutorialTextHeight: 40,
  tapCursorDisplayWidth: 140,
  tapCursorGapBelowText: 12,
  tapCursorChannelMargin: 56,
} as const;
