/** Side-wall rock strips (generated by scripts/process_swimmer_side_walls.py). */

export const swimmerSideWallLeft = require('../../assets/swimmer/walls/side_wall_left.webp');
export const swimmerSideWallRight = require('../../assets/swimmer/walls/side_wall_right.webp');

/** Keys registered in RNTGE image cache via `<Asset type="image" name="…" />`. */
export const SWIMMER_SIDE_WALL_IMAGE_KEYS = [
  'side_wall_left',
  'side_wall_right',
] as const;

/** Native width / height from assets/swimmer/side-walls-meta.json. */
export const SWIMMER_SIDE_WALL_LEFT_ASPECT = 178 / 1592;
export const SWIMMER_SIDE_WALL_RIGHT_ASPECT = 183 / 1594;
