/** Swimmer obstacle block sprites (generated by scripts/process_swimmer_block_variations.py). */

import { intMod, mixU32 } from '@/Game/path/deterministicMix';

export const swimmerBlockVar0 = require('../../assets/swimmer/blocks/block_var_0.webp');
export const swimmerBlockVar1 = require('../../assets/swimmer/blocks/block_var_1.webp');
export const swimmerBlockVar2 = require('../../assets/swimmer/blocks/block_var_2.webp');
export const swimmerBlockVar3 = require('../../assets/swimmer/blocks/block_var_3.webp');

/** Keys registered in RNTGE image cache via `<Asset type="image" name="…" />`. */
export const SWIMMER_BLOCK_IMAGE_KEYS = [
  'block_var_0',
  'block_var_1',
  'block_var_2',
  'block_var_3',
] as const;

/** Opaque cell underlay — darkest clay ramp, blocks water through rounded sprite corners. */
export const SWIMMER_BLOCK_CELL_BACKING_COLOR = '#9A4518';

/** Exterior backing corner radius as fraction of min(cell width, height). */
export const SWIMMER_BLOCK_CELL_BACKING_CORNER_RADIUS_RATIO = 0.14;

/**
 * Spawn weight per variant (percent, sums to 100). Order matches `SWIMMER_BLOCK_IMAGE_KEYS`.
 * block_var_0: 58%, block_var_1: 6%, block_var_2: 12%, block_var_3: 24%
 */
export const SWIMMER_BLOCK_VARIANT_WEIGHTS = [58, 6, 12, 24] as const;

/** Cumulative upper bounds for weighted roll in [0, 100). */
const SWIMMER_BLOCK_VARIANT_CUMULATIVE = [
  SWIMMER_BLOCK_VARIANT_WEIGHTS[0],
  SWIMMER_BLOCK_VARIANT_WEIGHTS[0] + SWIMMER_BLOCK_VARIANT_WEIGHTS[1],
  SWIMMER_BLOCK_VARIANT_WEIGHTS[0] +
  SWIMMER_BLOCK_VARIANT_WEIGHTS[1] +
  SWIMMER_BLOCK_VARIANT_WEIGHTS[2],
] as const;

/** Deterministic weighted pick from world position (stable per block cell). */
export function pickSwimmerBlockImageStable(x: number, y: number): string {
  'worklet';
  const roll = intMod(
    mixU32(Math.round(x * 1000), Math.round(y * 1000), 713),
    100
  );
  if (roll < SWIMMER_BLOCK_VARIANT_CUMULATIVE[0]) {
    return SWIMMER_BLOCK_IMAGE_KEYS[0];
  }
  if (roll < SWIMMER_BLOCK_VARIANT_CUMULATIVE[1]) {
    return SWIMMER_BLOCK_IMAGE_KEYS[1];
  }
  if (roll < SWIMMER_BLOCK_VARIANT_CUMULATIVE[2]) {
    return SWIMMER_BLOCK_IMAGE_KEYS[2];
  }
  return SWIMMER_BLOCK_IMAGE_KEYS[3];
}

/** Must match `LAYOUT_CONSTANTS.COLUMNS` — local copy keeps this module worklet-safe (no Layout import). */
const SWIMMER_GRID_COLUMNS = 6;

/** Native sprite height / width (average of assets/swimmer/blocks-meta.json variants). */
export const SWIMMER_BLOCK_HEIGHT_TO_WIDTH_RATIO = 515.5 / 462;

/** Average bottom-shadow depth / sprite height (from assets/swimmer/blocks-meta.json). */
export const SWIMMER_BLOCK_DEPTH_OVERLAP_RATIO = 0.1;

export type ObstacleBlockDimensions = {
  width: number;
  height: number;
};

function getObstacleColumnWidth(containerWidth: number): number {
  'worklet';
  return containerWidth / SWIMMER_GRID_COLUMNS;
}

export function getBlockDepthOverlap(blockHeight: number): number {
  'worklet';
  return blockHeight * SWIMMER_BLOCK_DEPTH_OVERLAP_RATIO;
}

export function getObstacleBlockHeightFromColumnWidth(columnWidth: number): number {
  'worklet';
  return columnWidth * SWIMMER_BLOCK_HEIGHT_TO_WIDTH_RATIO;
}

export function getObstacleBlockHeight(containerWidth: number): number {
  'worklet';
  return getObstacleBlockHeightFromColumnWidth(getObstacleColumnWidth(containerWidth));
}

export function obstacleBlockDimensionsFromColumnWidth(
  columnWidth: number
): ObstacleBlockDimensions {
  'worklet';
  return {
    width: columnWidth,
    height: getObstacleBlockHeightFromColumnWidth(columnWidth),
  };
}

export function getObstacleBlockDimensions(
  containerWidth: number
): ObstacleBlockDimensions {
  'worklet';
  return obstacleBlockDimensionsFromColumnWidth(getObstacleColumnWidth(containerWidth));
}

/** Vertical center-to-center spacing between stacked rows (includes depth overlap). */
export function getObstacleRowPitch(blockHeight: number): number {
  'worklet';
  return blockHeight - getBlockDepthOverlap(blockHeight);
}

/**
 * World Y for a new row stacked above `prevRowY`.
 * Each row after the first is lowered (positive Y) so it overlaps the row below's shadow.
 */
export function getNextObstacleRowY(
  prevRowY: number,
  blockHeight: number
): number {
  'worklet';
  return prevRowY - blockHeight + getBlockDepthOverlap(blockHeight);
}
