/** Extended uniforms for layered idle/general water visuals. */
export const waterLightingUniforms = `
  uniform float uVisualIntensity;
  uniform vec3 uWaterColorSurface;
  uniform vec3 uWaterColorMid;
  uniform vec3 uWaterColorDeep;
  uniform vec3 uWaterHighlight;
  uniform float uSurfaceHighlightThickness;
  uniform float uInternalCurrentOpacity;
  uniform float uInternalCurrentSpeed;
  uniform float uWallDarkening;
  uniform float uIdleMainWaveAmplitude;
  uniform float uIdleMainWaveSpeed;
  uniform float uIdleMainWaveSpatialFreq;
  uniform float uIdleSecondaryWaveAmplitude;
  uniform float uIdleSecondaryWaveSpeed;
  uniform float uIdleSecondaryWaveSpatialFreq;
  uniform float uIdleMaxCombinedAmplitude;
  uniform float uIdleBreathingAmount;
  uniform float uIdleBreathingSpeed;
  uniform float uInternalShapeOpacity;
  uniform float uRiseStreakIdleOpacity;
  uniform float uRiseStreakActiveOpacity;
  uniform float uRiseStreakIdleSpeed;
  uniform float uRiseStreakActiveSpeedScale;
  uniform float uRiseStreakLongChance;
  uniform float uBubbleIdleOpacity;
  uniform float uBubbleActiveOpacity;
  uniform float uBubbleIdleSpawnThreshold;
  uniform float uBubbleActiveSpawnThreshold;
  uniform float uBubbleCellWidthPx;
  uniform float uBubbleCellHeightPx;
  uniform float uBubbleMinRadiusPx;
  uniform float uBubbleMaxRadiusPx;
  uniform float uBubbleRiseIdleFactor;
  uniform float uBubbleRiseActiveFactor;
  uniform float uBubbleRiseFromWaterSpeed;
`;
